### ISSUE TITLE
Material's Texture Resolution Impacts Performance Immensely

### ISSUE THREAD

**Issue by simonSkrippek** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#1]
I started using this shader and it's great, no doubt about that.
However, the framerate dropped to about 1/50th, and the game was barely playable anymore. The reason was a too high-resolution texture, that I used for the material.
I do not know if this is somehow "fixable", but maybe include it in the recommendations for improving performance.

Anyhow, thanks you very much for a great shader.

**Comment by ColinLeung-NiloCat** [comment]
did you enable the "generate mipmap" in that high-resolution texture?
if yes, but the performance is still bad, then it is a problem

**Comment by simonSkrippek** [comment]
no, i did not, didn't know that would change performance. thanks for pointing that out

**Comment by ColinLeung-NiloCat** [comment]
I added a note in readme, I will close this issue now. If performance is still slow, please open a new issue.

new note = 
"enable "generate mipmap" for your decal texture, else a high resolution decal texture will make your game slow due to cache miss in GPU memory"
