### ISSUE TITLE
Decals work on scene view, but not in game view

### ISSUE THREAD

**Issue by mxaddict** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#10]
![image](https://user-images.githubusercontent.com/1060905/83953204-e5987980-a870-11ea-97a0-3265b35a0618.png)

![image](https://user-images.githubusercontent.com/1060905/83953210-eaf5c400-a870-11ea-97b0-9afad9d3ca2f.png)

**Comment by ColinLeung-NiloCat** [comment]
what is your 
- platform (PC? iOS?)
- URP version
- unity version

**Comment by mxaddict** [comment]
OS: Windows 10 64bit 1903
Unity: 2019.3.15f1
URP: 7.3.1

**Comment by ColinLeung-NiloCat** [comment]
just to make sure, did you turn on depth texture in URP's setting?

**Comment by mxaddict** [comment]
> just to make sure, did you turn on depth texture in URP's setting?

I did not 😄 Is that mentioned somewhere in the readme?

**Comment by mxaddict** [comment]
That seems to have fixed the rendering of the decal
![image](https://user-images.githubusercontent.com/1060905/83974925-56986980-a923-11ea-8301-df0a4738e3fe.png)

**Comment by mxaddict** [comment]
But, I have a different issue, seems my character weapon is being rendered before the decal.

What render step is the decal rendered on?

![image](https://user-images.githubusercontent.com/1060905/83974948-7891ec00-a923-11ea-862a-8b1f3780e3e3.png)

**Comment by mxaddict** [comment]
NVM, I've fixed it, I just set my weapon/player models to render after transparents

**Comment by ColinLeung-NiloCat** [comment]
I will add a more clear note of "enable depth texture" in readme, thanks!

**Comment by mxaddict** [comment]
Thanks, this is amazing!

![image](https://user-images.githubusercontent.com/1060905/83975118-a166b100-a924-11ea-9f9e-2ce0480a8c72.png)

**Comment by mxaddict** [comment]
I'll add you to my credits section of the game I'm working on 😄 it's the least I can do.
