### ISSUE TITLE
Not really an issue, but more like a question

### ISSUE THREAD

**Issue by mxaddict** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#11]
I know that the decal shader will supper wrapping, but I also know what you need to have the cube facing the right direction to get it to wrap correctly.

I currently have a raycast that gets the position and normal (direction) to place the cube (with the shader for decal)

But the issue I'm facing is when it hits near the mesh edge, is there a way to have the rotation of the cube be adjusted based on the normal of the edge face of the mesh as well?

**Comment by mxaddict** [comment]
This is what the issue looks like:

![image](https://user-images.githubusercontent.com/1060905/84135996-44324300-aa7d-11ea-9530-65dcf5b99b68.png)

**Comment by mxaddict** [comment]
![image](https://user-images.githubusercontent.com/1060905/84136048-58764000-aa7d-11ea-85ce-d5d81a99cb14.png)

**Comment by mxaddict** [comment]
What i'd like to do is slightly rotate the decal cube to be like so:
![image](https://user-images.githubusercontent.com/1060905/84136228-96736400-aa7d-11ea-976c-3aac5164c6fd.png)

![image](https://user-images.githubusercontent.com/1060905/84136320-b4d95f80-aa7d-11ea-9483-79c61e3c4a1b.png)

**Comment by mxaddict** [comment]
Actually, now that I think about it, how it the image projected onto the object? Does the shader decide the direction of the projection? 👍

**Comment by ColinLeung-NiloCat** [comment]
try turn on _ProjectionAngleDiscardEnable, and adjust _ProjectionAngleDiscardThreshold

**Comment by mxaddict** [comment]
> try turn on _ProjectionAngleDiscardEnable, and adjust _ProjectionAngleDiscardThreshold

Thanks, I'll try that.

**Comment by mxaddict** [comment]
This is the effect that I'm getting
![image](https://user-images.githubusercontent.com/1060905/84192153-2a6c1c80-aacc-11ea-943d-4290a5c6764e.png)

**Comment by mxaddict** [comment]
Hmmm, just did some tweaking, seems that my cube works better if rotated backwards? Does that make any sense? 🗡️ 

Basically I have this now:
```csharp
Quaternion.FromToRotation(Vector3.forward * -1, hit.normal)
```
