### ISSUE TITLE
Decal isn't visible in Game / Game view window

### ISSUE THREAD

**Issue by AntonioCaroppos** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#12]
Unity 2020.1.0b14.4034
URP: 8.1.0

In the scene view windows, all is fine.
In the game view window, the decal isn't visible.

![ss1](https://user-images.githubusercontent.com/29504639/87054345-49f98080-c203-11ea-9ff4-8e3faf6836d3.png)

**Comment by AntonioCaroppos** [comment]
![laserdot](https://user-images.githubusercontent.com/29504639/87054428-62699b00-c203-11ea-91e5-444a4257d94e.png)
![dot1](https://user-images.githubusercontent.com/29504639/87054472-73b2a780-c203-11ea-8b89-7a5a3ed22191.png)
![settings1](https://user-images.githubusercontent.com/29504639/87054550-875e0e00-c203-11ea-87ec-bb9d27cfc9dc.png)

**Comment by ColinLeung-NiloCat** [comment]
is depth texture enabled?

**Comment by ColinLeung-NiloCat** [comment]
search UniversalRP-HighQuality, see if depth texture is enabled

**Comment by AntonioCaroppos** [comment]
Thank you very much.
Activation "depth texture" resolved the problem.
