### ISSUE TITLE
Question about rotation

### ISSUE THREAD

**Issue by tw2021** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#14]
Dear Colin,

thank you so much for your URP Decal Shader!

I want to create a laser dot like in RE4. 

Here is a [video](https://youtu.be/dMlqxYRJGaw) of my current approach.

I have created cube and assigned a material with a dot and your shader.
The cube is placed via a raycast under the mouse position.

As you can see in the video, it works great if the projection angle is correct.
However, when the cube / geometry is not in the correct angle, the circle becomes a rectangle. 
I guess I need to rotate the cube correctly towards the geometry? 

Can you recommend how to keep the laser dot in the "correct" angle? 
Is there a preferred solution for this?

Thank you very much!

![laser1](https://user-images.githubusercontent.com/68448523/87865120-877fab80-c971-11ea-90b0-05f71b904599.png)

**Comment by ColinLeung-NiloCat** [comment]
You can use raycast's hit information's norrmal vector to "LookAt()" the cube's transform in the opposite direction

**Comment by tw2021** [comment]
Thank you, I have tried that with the following script on my gun:

    void Update()
    {
        var mousePos = Input.mousePosition;
        mousePos.z = Camera.main.farClipPlane;

        Ray ray = Camera.main.ScreenPointToRay(mousePos);

        RaycastHit hit;
        if (Physics.Raycast(ray, out hit))
        {
            Vector3 target = hit.point;

            transform.LookAt(hit.point);//aim the gun at the point in worldspace

            DecalCube.position = hit.point;//position the decal where the ray hits

            // Find the line from the gun to the point that was clicked.
            Vector3 incomingVec = hit.point - transform.position;

            // Use the point's normal to calculate the reflection vector.
            Vector3 reflectVec = Vector3.Reflect(incomingVec, hit.normal);

            DecalCube.transform.LookAt(reflectVec);
        }

I see some rotation on the cube that has the decal material on it, but the results don't look right: I still get the rectangle material.

To debug what is happening, I have then put a standard material onto the cube instead. This way I can see what the rotation looks like:

![diff1](https://user-images.githubusercontent.com/68448523/87870930-d4cd3e80-c9ac-11ea-859b-b51fd2498314.png)

Do you think the rotation looks correct?

**Comment by ColinLeung-NiloCat** [comment]
use this
https://docs.unity3d.com/ScriptReference/RaycastHit-normal.html

**Comment by tw2021** [comment]
I have used exactely this example.

**Comment by ColinLeung-NiloCat** [comment]
try
DecalCube.position = hit.point;
DecalCube.forward = -hit.normal;

**Comment by tw2021** [comment]
This looks good for me. The cube is rotated nicely towards the surface, but the decal doesn't look right to me.
I have recorded a [1-minute-video here](https://www.youtube.com/watch?v=1CyugQlm9c8).

First, I use a standard material on the cube to visualize the rotation nicely.
Then I put the decal material on it.
The decal doesn't look right to me.
Is there any setting in the Shader that could solve my issue?

**Comment by ColinLeung-NiloCat** [comment]
the video is quite blurry, I can't see the result.
Will toggle _ProjectionAngleDiscardEnable ON solve the issue?

**Comment by tw2021** [comment]
I don't think so.
I have recorded a [better video here](https://www.youtube.com/watch?v=6-3LCtgcL-4).
Could you please have a look again?

**Comment by ColinLeung-NiloCat** [comment]
Thanks for the better video, It is HD and I can understand the problem now.
(1) toggle _ProjectionAngleDiscardEnable ON
(2) edit _ProjectionAngleDiscardThreshold until the problem is solved

**Comment by tw2021** [comment]
Thank you, it's better now, but on the edges, the decal disappears in certain situations.
Here are 2 videos that show this:

[Video 1](https://youtu.be/h_hU2cYQOcs)
[Video 2](https://youtu.be/-heKbfjpW4A)

**Comment by ColinLeung-NiloCat** [comment]
try make the cube very thin,

**Comment by tw2021** [comment]
This improves it, but it isn't a solution. It keeps disappearing sometimes, and I don't see why.
Would you like me to provide you my sample project?

**Comment by tw2021** [comment]
This is what it currenty looks like for me: https://www.youtube.com/watch?v=TTRcVaeEjnI

**Comment by ColinLeung-NiloCat** [comment]
maybe too thin

**Comment by tw2021** [comment]
Hmmm, I don't think so.
Can you have a look at the rotation? https://www.youtube.com/watch?v=jYRgmZZo_XM
Can you have a look at the left side where you see the cube? When the decal disappears on the right side, the rotation looks strange in the Scene View window.
Perhaps the rotation formula is not correct?

**Comment by tw2021** [comment]
Here is a video where the rotation can be seen better:

https://youtu.be/DT3w2IyHN2k

At some points, the cube isn't put on the object anymore. You can see it in the Scene View.

**Comment by tw2021** [comment]
I think it's a collider issue. I will isolate the problem first.

**Comment by tw2021** [comment]
My last question, I hope:

![edge](https://user-images.githubusercontent.com/68448523/87873700-ea019780-c9c3-11ea-9ac1-8f43d1f522ce.png)

Currently, on the edges, the decal goes either on the top or onto the bottom of the cube.
Is there a way to show it on both top and bottom somehow? 

Can you suggest how I have to change 

            DecalCube.forward = -hit.normal;

to do that?

**Comment by tw2021** [comment]
Yipppieeeeeeeeeee, I got it:

            DecalCube.position = hit.point;//position the decal where the ray hits
            DecalCube.LookAt(new Vector3(hit.point.x, hit.point.y, 0));

Thank you so much!!
