### ISSUE TITLE
is uv bug?

### ISSUE THREAD

**Issue by liange** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#18]
code at line 176,
float2 decalSpaceUV = decalSpaceScenePos.xy + 0.5;
if the cube has no roation, should decalSpaceScenePos.xy as decalSpaceScenePos.xz?

**Comment by ColinLeung-NiloCat** [comment]
use .xy will make decal projection projects towards cube's forward direction

**Comment by ColinLeung-NiloCat** [comment]
you can change to .xz if you like it

**Comment by liange** [comment]
ok, thanks
