### ISSUE TITLE
Decals moving up/down at runtime.

### ISSUE THREAD

**Issue by kamgam** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#19]
First, thank you for making this open source.

I have a little trouble getting this to work at runtime / game view. It works in the Editor Scene View. I am using Unity 2019.4.1f1 and URP 7.3.1., Target "Android", the "Depth Texture" settings is enabled.

I have created an animated gif to show what is happening:
https://kamgam.com/unity/decal-shader-test.gif

I have also purchased the "Lux Shader" package you have recommended to another user (issue #9) but there seems to be the same issue. Any ideas on what might cause this?

**Comment by kamgam** [comment]
Update: got it to work with adding a "Renderer Feature" with the default settings. Not sure what this does though. It seems to work now. Is this required for the shader to work?

**Comment by kamgam** [comment]
Thanks for your reply. I just realized that the queue was not visible in my gif, sorry for that. It is set to 2501 (from shader). Increasing it does not change the outcome. Reducing it makes it vanish at some point (1000ish range, far from 2501).
If I inspect the scenes rendering on the Frame Debugger I see the decal shader right after the depth texture write. Not sure if it's relevant, I am using "linear" color space.

I have composed an image of all my settings, maybe you can spot my error.

![decal-shader-test2](https://user-images.githubusercontent.com/51050402/91023304-ab7c7f80-e5f6-11ea-8e8e-4605f2b9f292.png)

Thank you for your effort.

**Comment by SanyaBane** [comment]
If that's still relevant.

Make sure "Post Processing" is turned on, on your game camera. 
At least this helped me with simillar (or maybe even the same) problem.

![image](https://user-images.githubusercontent.com/10571568/94348868-5e9e2580-0048-11eb-8c6f-da5ec7d25fa4.png)

**Comment by kamgam** [comment]
Thank you @SanyaBane for your comment and sorry for my late reply. Indeed that solved it for me. In my project there was some code which turned off Post Processing at runtime based on performance, so whenever I checked in Edit mode it showed as being turned on *sigh*. Thanks for the reminder and also thanks again to @ColinLeung-NiloCat . Sometimes you just can't see the forest for the trees.
