### ISSUE TITLE
Weird Artifacts in Unity 2019

### ISSUE THREAD

**Issue by nagato1995** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#2]
Hello, thank you for creating this decal shader.  I pasted the shader code in a newly created Unlit shader. Upon compiling the shader and assigning the material to the cube weird artifacts are found instead of the designated texture. I am providing the texture along with the artifact  created by using this shader.

PS: English is not my native language, please do not mind any errors :)
![blood decal aritifact](https://user-images.githubusercontent.com/62143964/76677204-8f10fb80-65f1-11ea-9e33-3225a686ec12.jpg)

![Original Blood Texture](https://user-images.githubusercontent.com/62143964/76626671-9b4c7880-655f-11ea-9805-0fa44def5b14.jpg)

**Comment by ColinLeung-NiloCat** [comment]
try to rotate the decal game object 90 degrees, the decal game object's local Z axis (blue arrow), should be always pointing to the projection direction

**Comment by ColinLeung-NiloCat** [comment]
please open a new issue if the problem still exists, I will close it now
