### ISSUE TITLE
Question about clip

### ISSUE THREAD

**Issue by Adwerk** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#20]
Hey Colin, thanks a lot for sharing the decal shader.
I was wondering, whats the best approach when it comes to implementing a "fade" functionality to the shader (the usual way of clipping using alpha to make it dissolve)? I've been trying myself, but I tend to end up breaking the mask, making it project in all directions.

Sorry for the newbi question :)

-Cheers.

**Comment by ColinLeung-NiloCat** [comment]
control _Color.a

**Comment by Adwerk** [comment]
Sorry, had been trying to get it working with different blend modes and texture setups - but the current one I was using didn't work with _Color.a. However after actually changing to the defaults you state, its working of cause :D

Thanks for the help man, cheers.

**Comment by Adwerk** [comment]
Close
