### ISSUE TITLE
Including problem with this Shader

### ISSUE THREAD

**Issue by pabatribick** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#24]
If I'm copy with .shader File Unity throws me out an error with this Line of Code:

#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

![error](https://user-images.githubusercontent.com/11978788/100623619-b136df00-3322-11eb-928f-937310bb9d6b.PNG)

How to fix that? Unity Version 2019.2.11 with LWRP-HighQuality

**Comment by ColinLeung-NiloCat** [comment]
try URP, not LWRP

**Comment by ColinLeung-NiloCat** [comment]
I retested the shader using 2020.2.01f, URP 10.2.2, PC editor, android build.
I can confirm the problem doesn't exist in 2020.2.01f, URP 10.2.2, PC editor, android build, so I will close this issue.
If you find any new bug/problem still exist, please open a new issue, thanks!
