### ISSUE TITLE
Can't set decal to be transparent right.

### ISSUE THREAD

**Issue by mypaxa00** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#26]
I want that texture alpha 0 be transparent at rendering, how can I achieve this??
![Unity_tSQaxaYGZN](https://user-images.githubusercontent.com/36297589/104916205-689eb800-599a-11eb-82d4-754d53e09e49.png)

**Comment by ColinLeung-NiloCat** [comment]
https://github.com/ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#i-can-see-decal-renders-correctly-but-which-blendmode-should-i-use-in-the-material-inspector

Blend SrcAlpha OneMinusSrcAlpha // Traditional transparency

**Comment by mypaxa00** [comment]
That why I'm asking, because none of those blend modes works. At least for me.
![Unity_PLBSCOeC0T](https://user-images.githubusercontent.com/36297589/104931284-dce35680-59ae-11eb-8aa4-af4f64637eab.jpg)

**Comment by ColinLeung-NiloCat** [comment]
_AlphaRemap use (1,0,0,0)

**Comment by mypaxa00** [comment]
Perfect. thanks.
