### ISSUE TITLE
How can I ignore something?

### ISSUE THREAD

**Issue by OtakuAndFitness** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#29]
I don't want something to receive the decal, but others need to be received. 

Stencil test can achieve that?

**Comment by ColinLeung-NiloCat** [comment]
your "don't want to receive decal" objects need to draw first and write value K into stencil,
then you render the decal, which only pass the stencil test when stencil != K

**Comment by OtakuAndFitness** [comment]
Cheers!  I Made it!
