### ISSUE TITLE
Decal not showing in the Game view

### ISSUE THREAD

**Issue by aalexxjaz** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#4]
![image](https://user-images.githubusercontent.com/59322368/78460299-ffc2a980-76bf-11ea-9361-b1206f33d804.png)
As you can see its in the scene but I cant see it with my camera. I am already using depth texture (nothing changed).

**Comment by ColinLeung-NiloCat** [comment]
is it working fine in scene view?

**Comment by ColinLeung-NiloCat** [comment]
you can buy professional production-ready URP shaders here,
https://assetstore.unity.com/packages/vfx/shaders/lux-urp-lwrp-essentials-150355

**Comment by aalexxjaz** [comment]
Yeah! In the scene view its working, but the camera wont see it

**Comment by aalexxjaz** [comment]
So, I found it. I created a new project with URP already installed and there it worked. Now I compared it to my project, that previously was a normal project. The difference was this: 
![image](https://user-images.githubusercontent.com/59322368/78508716-4af4bf00-7789-11ea-8a20-49cdf7420797.png)

Now Im using the HighQuality Asset, copied from the new project. Previously I was using a new created asset and tried to setup it.

**Comment by firdiansyah-ramadhan-programmer** [comment]
no it is not matter of High Quality RP.
its because the RP not enabled Depth Texture.
![image](https://user-images.githubusercontent.com/100658874/157216218-c35cd5c2-c836-4d8b-bc17-466255806fd3.png)
.
it is a late post but just in case somebody need it
