### ISSUE TITLE
Using custom meshes

### ISSUE THREAD

**Issue by KingOscarV** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#5]
Hi, I'm trying to make this work on the fovs that player units have in an rts game. The thought is to give the ground a highlight to showcase what areas the player can see. So I create a mesh through a script to visualize this area and then use this shader to make it highlight the ground where the mesh intersects with the ground. The problem is that it doesn't work, I've made this shader work with Unity's cube mesh but when using the mesh I created it doesn't render anything on the ground. Do you have any ideas what the problem could be related to? I don't know a lot about meshes, so it's possible that I've set up normals, uvs etc... wrong.

https://gyazo.com/f73f25ce00ca31a9b331ea59f1c364e0

**Comment by ColinLeung-NiloCat** [comment]
because that decal shader was written only for unity cube mesh.
So it is correct that it won't work for your custom mesh

**Comment by ColinLeung-NiloCat** [comment]
in this case, you will need to write the fov shape code directly inside the decal shader's fragment shader.

Imagine you use the decal shader to draw a full 360 circle on ground(use unity cube mesh to render) as normal.

then you add a slider to control which area of the circle should show base on fob, by editing the fragment shader.

**Comment by KingOscarV** [comment]
Thanks for the response. 
I'm also having an idea that instead of constructing a mesh to represent the fov I create a 2D texture instead. That way I can use the cube mesh to render the texture I created. I think I'll try that approach first since I find shaders scary and try to avoid them as best I can ^^
Anyways cheers 
// Oscar

**Comment by ColinLeung-NiloCat** [comment]
It will work, no matter "create a fov texture" / "create a fov shape in shader",  the visual result will be the same. 

but if the fov changes a lot in gameplay, writing the fov shape inside shader will have much much better performance.
