### ISSUE TITLE
Transparent plane

### ISSUE THREAD

**Issue by Blocovin** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#7]
Hi, this shader doesn't seem to work when intersected object is transparent. Any solution ? Thank for your work.

**Comment by ColinLeung-NiloCat** [comment]
to do this, your transparent object need to render to depth texture, but doing this will produce other problems. There is no perfect solution to this problem.

**Comment by Blocovin** [comment]
Ok thanks. We will use "Mesh decals" instead of "Screen space decal".
