### ISSUE TITLE
Support orthographic projection

### ISSUE THREAD

**Issue by zwcloud** [ColinLeung-NiloCat/UnityURPUnlitScreenSpaceDecalShader#9]
The decal won't be displayed if the camera uses orthographic projection.

![decal_ortho](https://user-images.githubusercontent.com/6965758/83941071-f918f580-a81a-11ea-9c09-15b01b4f1c84.gif)

**Comment by ColinLeung-NiloCat** [comment]
try this if you want a decal shader that support this function
https://assetstore.unity.com/packages/vfx/shaders/lux-urp-lwrp-essentials-150355

**Comment by zwcloud** [comment]
Is *Lux URP/LWRP Essentials* your product? And this repo is only used to advertise that?

I want to know how to solve this problem based on current implmentation of UnityURPUnlitScreenSpaceDecalShader. Any ideas?

**Comment by ColinLeung-NiloCat** [comment]
>Is Lux URP/LWRP Essentials your product? And this repo is only used to advertise that?
No.

>I want to know how to solve this problem based on current implmentation of UnityURPUnlitScreenSpaceDecalShader. Any ideas?

yes it is possible, but I can't post it here, because I learn it from Lux URP/LWRP Essentials

**Comment by lassade** [comment]
I kind managed to get this effect to work in the orthographic camera as well as perspective;

Replace the `LinearEyeDepth` function in line 169 by the `Correct Depth` function below

```
float CorrectDepth(float rawDepth)
{
	float persp = LinearEyeDepth(rawDepth, _ZBufferParams);
	float ortho = (_ProjectionParams.z - _ProjectionParams.y) * (1 - rawDepth) + _ProjectionParams.y;
	return lerp(persp, ortho, unity_OrthoParams.w);
}
```

Sadly I'm still getting very weird distortions

**Comment by ColinLeung-NiloCat** [comment]
added _SupportOrthographicCamera toggle, turn it ON if orthographic camera is needed
